# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('isFree', models.BooleanField(default=False)),
                ('city_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City')),
            ],
        ),
    ]
